# PyTorch Crash Course: Deep Learning in Python

https://youtu.be/uq7sbUlIDR8

In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
torch.cuda.device_count()

0

In [4]:
# run if have cuda device to get name
# torch.cuda.get_device_name(0)

In [5]:
torch.cuda.device(0)

## Tensors

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 5], [1, 2, 3, 5]])
arr

array([[1, 2, 3, 5],
       [1, 2, 3, 5]])

In [7]:
tensor = torch.Tensor([[1, 2, 3, 5], [1, 2, 3, 5]])
tensor, tensor.shape

(tensor([[1., 2., 3., 5.],
         [1., 2., 3., 5.]]),
 torch.Size([2, 4]))

In [8]:
arr * 5

array([[ 5, 10, 15, 25],
       [ 5, 10, 15, 25]])

In [9]:
tensor * 5

tensor([[ 5., 10., 15., 25.],
        [ 5., 10., 15., 25.]])

In [10]:
arr.sum(), tensor.sum()

(np.int64(22), tensor(22.))

In [11]:
tensor = torch.from_numpy(arr)
tensor # will be integers because created from numpy array

tensor([[1, 2, 3, 5],
        [1, 2, 3, 5]])

In [12]:
np.ones([2, 4]), torch.ones([1, 2])

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 tensor([[1., 1.]]))

In [13]:
np.random.random((2, 4)), torch.rand((1, 2))

(array([[0.85629412, 0.32553043, 0.44838113, 0.95732332],
        [0.85815802, 0.39464464, 0.15928493, 0.37870598]]),
 tensor([[0.6186, 0.9436]]))

In [14]:
arr.shape, tensor.shape, arr.dtype, tensor.dtype, tensor.device

((2, 4), torch.Size([2, 4]), dtype('int64'), torch.int64, device(type='cpu'))

In [15]:
# run if CUDA is configured (GPU is available)
# tensor.to_device('cuda')

In [16]:
# run if have cuda configured
# tensor = tensor.to('cuda')
# tensor.sum() # now sum will be calculated on GPU

# This will give an error if the tensor is on GPU
# tensor.numpy()

In [17]:
tensor.cpu().numpy()

array([[1, 2, 3, 5],
       [1, 2, 3, 5]])

In [18]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## Automatic Differentiation

In [19]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [20]:
# f.sum(), f.sum().backward(), f, f.sum()

In [21]:
f.backward(gradient=torch.tensor([1, 1])) # [1, 1] means treat both equally

In [22]:
a.grad

tensor([36., 81.])

In [23]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [24]:
b.grad

tensor([-12.,  -8.])

In [25]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)

## DataLoader in PyTorch

In [26]:
from torch.utils.data import DataLoader, TensorDataset

# for loading dataset
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [27]:
# load the dataset from sklearn
X, y = load_breast_cancer(return_X_y=True)
X[0], y[0]

(array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]),
 np.int64(0))

In [28]:
# split 20% test data for testing the model after training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# scaling ensures all features contribute equally
# normalized feature vectors: have better performance in neural networks
scaler = StandardScaler()

# learn mean/std on training data
X_train_scaled = scaler.fit_transform(X_train)

# apply the learned mean/std from training data here
X_test_scaled = scaler.transform(X_test)

In [29]:
X_train_scaled[0], X_test_scaled[0]

(array([-0.34846761, -0.80628277, -0.35579456, -0.4010527 , -0.43493996,
        -0.41717617, -0.38151169, -0.46315865, -0.37686951, -0.5503274 ,
        -0.89486714, -1.3195258 , -0.79932408, -0.60489801, -0.71644821,
        -0.43131656,  0.02625689, -0.55237803, -0.56155593, -0.58958946,
        -0.43309466, -1.0155293 , -0.40161793, -0.46668534,  0.00739496,
         0.03332044,  0.3554656 , -0.24503542,  0.18216   , -0.35108957]),
 array([-0.69587126,  1.22141749, -0.7089959 , -0.65291282, -1.5493393 ,
        -0.89344171, -0.85387418, -0.91202051,  0.44550412, -0.59992202,
        -0.53929679,  0.98682639, -0.4359259 , -0.4664692 , -0.30799253,
        -0.13602786, -0.50973267, -0.76746004,  1.37672912, -0.61957342,
        -0.77354187,  0.96864078, -0.75106756, -0.69284271, -1.58596114,
        -0.76181527, -0.94347721, -0.99054736,  0.5738152 , -0.95732988]))

In [30]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()

y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1) # make it a column vector
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1) # make it a column vector

In [31]:
X_train_scaled_tensor.shape, X_test_scaled_tensor.shape, y_train_tensor.shape, y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455, 1]),
 torch.Size([114, 1]))

In [32]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)

In [33]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

## Build Neural Network Model

In [34]:
import torch.nn as nn
import torch.nn.functional as F # activation function
import torch.optim as optim # for optimizer

# define neural network architecture
class BCNet(nn.Module):
    def __init__(self):
        super(BCNet, self).__init__()

        self.fcl = nn.Linear(
            30, 64
        )  # input features = 30, output features = 64 will be given to the next layer
        self.fcl2 = nn.Linear(
            64, 32
        )  # input features = 64, output features = 32 will be given to the next layer
        self.fcl3 = nn.Linear(
            32, 1
        )  # input features = 32, output features = 1 will be the actual output of the model (probability of being malignant)

    def forward(self, x):
        x = F.relu(self.fcl(x))  # relu activation function to introduce non-linearity
        x = F.relu(self.fcl2(x))  # relu activation function to introduce non-linearity
        x = F.sigmoid(
            self.fcl3(x)
        )  # sigmoid to get output between 0 and 1 (probability)

        return x

In [35]:
model = BCNet()

In [36]:
criterion = (
    nn.BCELoss()
)  # binary cross entropy loss for binary classification - loss function to optimize
optimizer = optim.Adam(
    params=model.parameters(), lr=0.001
)  # Adam optimizer with learning rate of 0.001 - optimization algorithm to update weights

In [37]:
# training loop
epochs = 20

for epoch in range(epochs):
    model.train()  # set model to training mode
    running_loss = 0.0
    
    for x_batch, y_batch in train_loader:
        optimizer.zero_grad()  # zero the gradients before backpropagation

        preds = model(x_batch)  # forward pass to get predictions
        loss = criterion(preds, y_batch)  # calculate loss
        
        loss.backward()  # backpropagation to calculate gradients
        
        optimizer.step()  # update weights based on gradients
        
        running_loss += loss.item() # accumulate loss for the epoch
    print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(train_loader):.4f}")

Epoch 1/20, Loss: 0.6226
Epoch 2/20, Loss: 0.4416
Epoch 3/20, Loss: 0.2628
Epoch 4/20, Loss: 0.1829
Epoch 5/20, Loss: 0.1220
Epoch 6/20, Loss: 0.0982
Epoch 7/20, Loss: 0.0840
Epoch 8/20, Loss: 0.0742
Epoch 9/20, Loss: 0.0679
Epoch 10/20, Loss: 0.0627
Epoch 11/20, Loss: 0.0605
Epoch 12/20, Loss: 0.0566
Epoch 13/20, Loss: 0.0509
Epoch 14/20, Loss: 0.0483
Epoch 15/20, Loss: 0.0472
Epoch 16/20, Loss: 0.0441
Epoch 17/20, Loss: 0.0416
Epoch 18/20, Loss: 0.0396
Epoch 19/20, Loss: 0.0394
Epoch 20/20, Loss: 0.0370


## Evaluation on test set

In [38]:
with torch.no_grad():  # no need to calculate gradients for evaluation
    model.eval()  # set model to evaluation mode

    preds = model(X_test_scaled_tensor)  # get predictions for test data
    
    loss = criterion(preds, y_test_tensor)  # calculate loss on test data
    print(f"Test Loss: {loss.item():.4f}")
    
    accuracy = (( preds > 0.5) == y_test_tensor).float().mean().item() # calculate accuracy by comparing predictions to true labels
    print(f"Test Accuracy: {accuracy:.4f}")

Test Loss: 0.0467
Test Accuracy: 0.9912
