In [3]:
import torch

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
x[3]

tensor(3.)

In [9]:
x.reshape(3, -1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
torch.zeros((2, 3, 4,))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)

tensor([[-0.3007, -0.6979, -2.8710, -2.0205],
        [ 1.2499, -0.4696,  1.7112,  2.3103],
        [-0.6544,  0.1674,  0.4776, -1.3546]])

In [14]:
torch.tensor(
    [
        [2, 1, 4, 3],
        [1, 2, 3, 4],
    ]
)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4]])

In [15]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [16]:
X[1: 3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [23]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [25]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([8.0, 7.0, 6.0])
x+y, x-y, x*y, x/y, x**y

(tensor([9., 9., 9.]),
 tensor([-7., -5., -3.]),
 tensor([ 8., 14., 18.]),
 tensor([0.1250, 0.2857, 0.5000]),
 tensor([  1., 128., 729.]))

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [29]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [30]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [31]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
X.sum()

tensor(66.)

In [33]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [35]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [36]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [39]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 139778185788496
id(Z): 139778185788496


In [40]:
before = id(X)
X += Y
id(X) == before

True

In [41]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [42]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [43]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [44]:
X, Y

(tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]),
 tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

In [75]:
x = torch.rand(18, dtype=torch.float32).reshape(3, 3, 2)
y = torch.rand(18, dtype=torch.float32).reshape(3, 3, 2)
x, y

(tensor([[[0.4586, 0.7973],
          [0.3431, 0.0192],
          [0.7400, 0.1515]],
 
         [[0.2454, 0.2981],
          [0.4175, 0.0337],
          [0.2593, 0.3984]],
 
         [[0.0264, 0.4012],
          [0.2007, 0.1836],
          [0.4989, 0.5101]]]),
 tensor([[[0.2442, 0.2494],
          [0.9273, 0.5959],
          [0.0617, 0.6974]],
 
         [[0.1633, 0.3201],
          [0.1779, 0.9591],
          [0.3256, 0.3564]],
 
         [[0.1713, 0.4302],
          [0.7522, 0.0225],
          [0.9281, 0.6703]]]))

In [76]:
x==y

tensor([[[False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]]])

In [77]:
x < y

tensor([[[False, False],
         [ True,  True],
         [False,  True]],

        [[False,  True],
         [False,  True],
         [ True, False]],

        [[ True,  True],
         [ True, False],
         [ True,  True]]])

In [78]:
x > y

tensor([[[ True,  True],
         [False, False],
         [ True, False]],

        [[ True, False],
         [ True, False],
         [False,  True]],

        [[False, False],
         [False,  True],
         [False, False]]])

In [82]:
x / b

tensor([[[   inf, 0.7973],
         [   inf, 0.0192],
         [   inf, 0.1515]],

        [[   inf, 0.2981],
         [   inf, 0.0337],
         [   inf, 0.3984]],

        [[   inf, 0.4012],
         [   inf, 0.1836],
         [   inf, 0.5101]]])

In [83]:
x // y

tensor([[[ 1.,  3.],
         [ 0.,  0.],
         [11.,  0.]],

        [[ 1.,  0.],
         [ 2.,  0.],
         [ 0.,  1.]],

        [[ 0.,  0.],
         [ 0.,  8.],
         [ 0.,  0.]]])