# PyTorch Crash Course: Deep Learning in Python

https://youtu.be/uq7sbUlIDR8

In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
torch.cuda.device_count()

0

In [4]:
# run if have cuda device to get name
# torch.cuda.get_device_name(0)

In [5]:
torch.cuda.device(0)

## Tensors

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 5], [1, 2, 3, 5]])
arr

array([[1, 2, 3, 5],
       [1, 2, 3, 5]])

In [7]:
tensor = torch.Tensor([[1, 2, 3, 5], [1, 2, 3, 5]])
tensor, tensor.shape

(tensor([[1., 2., 3., 5.],
         [1., 2., 3., 5.]]),
 torch.Size([2, 4]))

In [8]:
arr * 5

array([[ 5, 10, 15, 25],
       [ 5, 10, 15, 25]])

In [9]:
tensor * 5

tensor([[ 5., 10., 15., 25.],
        [ 5., 10., 15., 25.]])

In [10]:
arr.sum(), tensor.sum()

(np.int64(22), tensor(22.))

In [11]:
tensor = torch.from_numpy(arr)
tensor # will be integers because created from numpy array

tensor([[1, 2, 3, 5],
        [1, 2, 3, 5]])

In [12]:
np.ones([2, 4]), torch.ones([1, 2])

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 tensor([[1., 1.]]))

In [13]:
np.random.random((2, 4)), torch.rand((1, 2))

(array([[0.22610659, 0.09307207, 0.00143254, 0.16558388],
        [0.26301938, 0.57722556, 0.49248562, 0.32077392]]),
 tensor([[0.3234, 0.2703]]))

In [14]:
arr.shape, tensor.shape, arr.dtype, tensor.dtype, torch.device

((2, 4), torch.Size([2, 4]), dtype('int64'), torch.int64, torch.device)

In [15]:
# run if cuda configured (gpu is available)
# arr.to_device('cuda')

In [16]:
# run if have cuda configured
# tensor = tensor.to('cuda')
# tensor.sum() # now sum will be calcualted on GPU

# this will give error if tensor is on GPU
# tensor.numpy()

In [24]:
tensor.cpu().numpy()

array([[1, 2, 3, 5],
       [1, 2, 3, 5]])

In [25]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## Automatic Differentiation

In [30]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [31]:
# f.sum(), f.sum().backward(), f, f.sum()

In [32]:
f.backward(gradient=torch.tensor([1, 1]))

In [33]:
a.grad

tensor([36., 81.])

In [34]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [37]:
b.grad

tensor([-12.,  -8.])

In [38]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)