# PyTorch Crash Course: Deep Learning in Python

https://youtu.be/uq7sbUlIDR8

In [1]:
import torch

In [3]:
torch.cuda.is_available()

False

In [4]:
torch.cuda.device_count()

0

In [13]:
# run if have cuda device to get name
# torch.cuda.get_device_name(0)

In [16]:
torch.cuda.device(0)

## Tensors

In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 5], [1, 2, 3, 5]])
arr

array([[1, 2, 3, 5],
       [1, 2, 3, 5]])

In [21]:
tensor = torch.Tensor([[1, 2, 3, 5], [1, 2, 3, 5]])
tensor, tensor.shape

(tensor([[1., 2., 3., 5.],
         [1., 2., 3., 5.]]),
 torch.Size([2, 4]))

In [22]:
arr * 5

array([[ 5, 10, 15, 25],
       [ 5, 10, 15, 25]])

In [23]:
tensor * 5

tensor([[ 5., 10., 15., 25.],
        [ 5., 10., 15., 25.]])

In [25]:
arr.sum(), tensor.sum()

(np.int64(22), tensor(22.))

In [27]:
tensor = torch.from_numpy(arr)
tensor # will be integers because created from numpy array

tensor([[1, 2, 3, 5],
        [1, 2, 3, 5]])

In [30]:
np.ones([2, 4]), torch.ones([1, 2])

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 tensor([[1., 1.]]))

In [35]:
np.random.random((2, 4)), torch.rand((1, 2))

(array([[0.38190054, 0.3988076 , 0.77035688, 0.19428939],
        [0.20628627, 0.29686629, 0.25130987, 0.06290445]]),
 tensor([[0.3276, 0.7559]]))

In [39]:
arr.shape, tensor.shape, arr.dtype, tensor.dtype, torch.device

((2, 4), torch.Size([2, 4]), dtype('int64'), torch.int64, torch.device)

In [43]:
arr.to_device('cuda')

ValueError: Unsupported device: cuda. Only 'cpu' is accepted.

In [53]:
# run if have cuda configured
# tensor = tensor.to('cuda')
# tensor.sum() # now sum will be calcualted on GPU

# this will give error if tensor is on GPU
# tensor.numpy()

In [54]:
tensor.cpu().numpy()

array([[1, 2, 3, 5],
       [1, 2, 3, 5]])

In [ ]:
# 11 Minutes Dones